### ISSUE TITLE
My favorite games

### ISSUE THREAD

**Issue by ASHIT-AXAR** [blahness/nes_test#2]
[Nintendo_MyFavoriteGames.zip](https://github.com/blahness/nes_test/files/1691965/Nintendo_MyFavoriteGames.zip)

it is very interesting to know there are peoples like me out there that play games from decades ego nowadays ...
:)

**Comment by blahness** [comment]
The music is screwed up in Bomberman & Lode Runner sadly.

**Comment by denizzzka** [comment]
Battletoads in fullscreen mode is bigger than 1920x1280

**Comment by blahness** [comment]
Fullscreen resolution should always be 720p. I'll look into it.
Battletoads will also freeze in level 2 because of a notorious PPU timing issue. See: http://forums.nesdev.com/viewtopic.php?t=6736.

**Comment by denizzzka** [comment]
Refinement: after F11 screen goes to a lower resolution. Then game screen placed higher than center. When you exit emulator resolution remains be low ("virtual desktop")

**Comment by denizzzka** [comment]
> Refinement: after F11 screen goes to a lower resolution. Then game screen placed higher than center. When you exit emulator resolution remains be low ("virtual desktop")

fixed in 0.1.2, thank!

**Comment by blahness** [comment]
You're welcome to try the newest version & see if it helps. It no longer assumes 720p is available in fullscreen.

**Comment by blahness** [comment]
Lol I was just about to ask that. Had to delete my comment even.
